### ISSUE TITLE
Android export error

### ISSUE THREAD

**Issue by johgun** [nathangross/figma-app-icon-exporter#1]
All Android icons except the 512x512 are 1px too large. A transparent pixel is added to the right and bottom of the exported image

**Comment by nathangross** [comment]
@johgun Sorry, I never saw a notification for this. It seems like the math I was using before on the exports is no longer working. I fixed it by just manually sizing an icon for each android icon. 

Updated and pushed. Let me know if you have any more issues. Thanks for posting the error here!
